let myResume={
    "basics": {
      "name": "RAMDEEPAK S",
      "email": "deepakram9467@gmail.com",
      "phone": 9500102001,8667628437
      "degree": "B.E MECHANICAL",
      "location": {
        "address": "16A,KUMARAN STREET,RAJESHWARI NAGAR,CAMPROAD,SELAIYUR",
        "postalCode": 600073,
        "city": "Chennai",
        "state": "Tamilnadu",
        "country": "India"
      },
      "profiles": [
        {
          "github":"https://github.com/Ramdeepak9466"
        }
      ]
    },
    "education": [
      {
        "institution": "SRI RAMANUJAR ENGG COLLEGE",
        "department": "Mechanical Engineering",
        "studyType": "fulltime",
        "batch start year": 2014,
        "batch end year": 2017,
        "gpa": 7.0,
      }
    ],
    "skills": [
      {
        "name": "python,javascript",
        "level": "beginner",
      }
    ],
    "languages": [
      {
        "language": "Tamil,English,Hindi,Malayalam",
      }
    ],
    "interests": [
      {
        "name": "Bike modifications and Long drives",
      }
    ]
  }
  console.log(myResume);